name: Trigger auto deployment for containerapp reddog-container-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ deployment ]
    paths:
    - '**'
    - '.github/workflows/reddog-container-app-AutoDeployTrigger-29900810-d778-42e5-9e2d-9c134fadef8b.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: sennaparsa.azurecr.io
          username: ${{ secrets.REDDOGCONTAINERAPP_REGISTRY_USERNAME }}
          password: ${{ secrets.REDDOGCONTAINERAPP_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: sennaparsa.azurecr.io/reddog-container-app:${{ github.sha }}
#           file: ./Dockerfile
#           context: ./
          context: .
          file: traefik/Dockerfile


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.REDDOGCONTAINERAPP_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            echo "Installing containerapp extension"
            az config set extension.use_dynamic_install=yes_without_prompt
            echo "Starting Deploying"
            az containerapp registry set -n reddog-container-app -g reddog --server sennaparsa.azurecr.io --username  ${{ secrets.REDDOGCONTAINERAPP_REGISTRY_USERNAME }} --password ${{ secrets.REDDOGCONTAINERAPP_REGISTRY_PASSWORD }}
            az containerapp update -n reddog-container-app -g reddog --image sennaparsa.azurecr.io/reddog-container-app:${{ github.sha }}
